### ISSUE TITLE
No such file or directory src/frontend/build/index.html'

### ISSUE THREAD

**Issue by songproducer** [amaclean199/soundscape-generator#4]
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/leotreasure/soundscape-generator/src/frontend/build/index.html'

**Comment by songproducer** [comment]
when running npm start in src/frontend
```
./src/components/player/AudioPlayer/AudioPlayerProvider.js
  Line 56:5:  Typo in component lifecycle method declaration  react/no-typos

Search for the keywords to learn more about each error.
```

**Comment by gregalexsmith** [comment]
Hi @songproducer, thanks for trying out the app!

Sorry for the lack of documentation on some of this, it's still in a bit of a hackathon state and not under active development, but any contributions are welcome!

> FileNotFoundError: [Errno 2] No such file or directory: '/Users/leotreasure/soundscape-generator/src/frontend/build/index.html'
- In development, you may need to run `npm run build` in `/src/frontend` in order for flask to interact with the compiled front-end application 


Had some trouble re-producing the second error, let me know if you have a fork to check-out, or any other information that might help!

**Comment by amaclean199** [comment]
Updated the README in 919300f805f534d184dae26ddd28626fc8e652ed to include instructions about `npm run build`
